### ISSUE TITLE
64-bit compatibility for iOS

### ISSUE THREAD

**Issue by knobel** [obscure-com/ti_keychain#10]
Apple is going to require 64 bit support in all application starting from 1st of February 2015 and Appcelerator is planning to release the 3.5.0 with 64bit support for iOS. The new SDK will require the modules to be 64-bit compatible. The Alpha release of 3.5.0 SDK is already available: http://www.appcelerator.com/blog/2014/11/alpha-version-of-titanium-sdk-64-bit-support-now-available/

**Comment by ghost** [comment]
Hi.

Just come on to ask if you would have time to update the module for 64bit please, and noticed the above request. Hopefully you will be able to resolve this.

Thanks

**Comment by knobel** [comment]
Hi,

I am completely new to technology. I also don't know the Objective-C so at this time I can't help. Sorry.

BR,

MK

**Comment by knobel** [comment]
Beta Version of Titanium SDK 64-bit Support Now Available: http://www.appcelerator.com/blog/2014/12/beta-version-of-titanium-sdk-64-bit-support-now-available/

**Comment by pegli** [comment]
I've made iOS and Android builds of the module with the 3.5.0.Beta SDK:

  https://github.com/pegli/ti_keychain/releases/tag/2.1

This is a pre-release build of the module.  Once the 3.5.0 SDK is out, I'll rebuild and remove the "pre-release" tag.

**Comment by ghost** [comment]
Thank you :)

**Comment by pegli** [comment]
I've rebuilt the 2.1 release with SDK 3.5.0.GA -- you can download it from the Releases section of the project.
