### ISSUE TITLE
Allow for multiple keychain items to be created

### ISSUE THREAD

**Issue by dhcustom** [obscure-com/ti_keychain#2]
Please amend the sample code from Apple to support using multiple keychain items per app. It's very simple to fix, just replace two lines of code.

http://stackoverflow.com/a/5008417

Change:

```
[genericPasswordQuery setObject:identifier forKey:(id)kSecAttrGeneric];
```

to:

```
[genericPasswordQuery setObject:identifier forKey:(id)kSecAttrAccount];
```

and change:

```
[keychainItemData setObject:identifier forKey:(id)kSecAttrGeneric];
```

to:

```
[keychainItemData setObject:identifier forKey:(id)kSecAttrAccount];
```

**Comment by pegli** [comment]
Fixed as described.  You may need to clear and re-set your keychain items if you used the module prior to this change.
