### ISSUE TITLE
'Couldn't find module: com.obscure.keychain' on real device

### ISSUE THREAD

**Issue by rborsini** [obscure-com/ti_keychain#6]
Hi,
the module works fine in the simulator, but when I try to run the app into the device I get this message:

Couldn't find module:
com.obscure.keychain

Can you help me?
Thanks

**Comment by iotashan** [comment]
Let me guess.... iPhone 5S?

The module was not compiled with 64 bit support. Download the source, make the change (sorry, you'll have to google, I forget off the top of my head), recompile.

**Comment by rborsini** [comment]
No, I got this error also on an oldest iphone 3GS.

**Comment by gjmcginn** [comment]
I can confirm that I also get this on iPad.

[INFO] OS Name - ipad
[INFO] OS Type - 32bit
[INFO] OS Version - 7.1.1

It works on the emulator, all iOS versions including 32bit and 64bit.

**Comment by Eco-Surv-Matt-Marsland** [comment]
I am also experiencing this on iPad, 32 bit, iOS 7.11.

I have cleaned the project and have tested the module in a new project.  It works great in the simulator, but when the app is run on the device I get the error:
Couldn't find module: com.obscure.keychain.

It would be great if you could offer some suggestions or advice.

Thanks.

**Comment by ayapi** [comment]
hi, i had the same prob
Mac OS X 10.8.4 & iPod touch 5 (32bit) iOS 7.1

i found a solution

```
git clone git://github.com/pegli/ti_keychain
open ./ti_keychain/mobile/ios/keychain.xcodeproj
```

Select project "keychain" on Project Navigator(Left panel)
Open "TARGETS - keychain - Build Settings"
Edit "Build Active Architecture Only" value "Yes" to "No"

```
./build.py
```

i dont know a lot about xcode build settings
but it works for me
plz try it. thx

**Comment by pegli** [comment]
Thanks for the pointers to the problem with the configuration.  I've fixed the build settings so the module will run on both the simulator and device.  The module ZIP file in mobile/ios/dist has been updated.
