### ISSUE TITLE
Deletion of keychain data

### ISSUE THREAD

**Issue by winternet-studio** [obscure-com/ti_keychain#8]
Is the data in the keychain deleted when a user goes to the app listing in the settings and press "Clear data" for that app?

**Comment by pegli** [comment]
I wasn't able to find a definitive answer to the question of whether iOS deletes keychain data when the "Clear Data" button is pressed.  In my experience, keychain items can persist even after an app is deleted and reinstalled, so I wouldn't depend on clearing keychain items with the "Clear Data" button.  If you need to remove an item, use the `reset()` method provided on the KeychainItem object.

**Comment by winternet-studio** [comment]
I finally tried it, and at least in the Android simulator the data disappears when you clear the app data. I would assume it's the same on a real device...
